version: "3.9" # optional since v1.27.0
services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - host.docker.internal:host-gateway
  svr01:
    image: nginx
    ports:
      - 11080:80
    volumes:
      - ./svr00/nginx.conf:/etc/nginx/nginx.conf
      - ./svr00/index.html:/var/www/index.html
  svr02:
    image: nginx
    ports:
      - 12080:80
    volumes:
      - ./svr01/nginx.conf:/etc/nginx/nginx.conf
      - ./svr01/index.html:/var/www/index.html
